### ISSUE TITLE
Where can i find module "protos"?

### ISSUE THREAD

**Issue by diman-mich** [mmcloughlin/finsky#3]
Hello!
Thanks for finsky packet, but i have such problem at running

File "/Library/Python/2.7/site-packages/finsky/client.py", line 4, in <module>
    import protos.response_pb2
ImportError: No module named protos.response_pb2

What is "protos". I can't find to download this module in Google.
Give me link or pip command please

**Comment by mghadam** [comment]
Hey,

protos.response_pb2.py is in the finsky/protos directory

**Comment by diman-mich** [comment]
Thanks, i just didn't get to loook for this module in repository. Pip manager didn't set up module 'protos'.
