### ISSUE TITLE
Dead acknowledgement link

### ISSUE THREAD

**Issue by jasco** [mmcloughlin/finsky#7]
While passing through, the acknowledgement link for `Dima Kovalenko's reverse engineering of EncryptedPasswd` caught my eye, but I found the page to be a landing page offering it for sale.  Not sure if this is the same but I found this possibly related content https://kov4l3nko.github.io/blog/2014-06-09-about-encryptedpasswd/

**Comment by mmcloughlin** [comment]
Thanks for pointing this out! Fixed it.
